CREATE TYPE role_enum AS ENUM ('USER', 'ADMIN');

CREATE TABLE users (
   id BIGSERIAL PRIMARY KEY,
   username VARCHAR(50) UNIQUE NOT NULL,
   password VARCHAR(255) NOT NULL,
   email VARCHAR(100) UNIQUE NOT NULL,
   role role_enum NOT NULL,
   first_name VARCHAR(50),
   last_name VARCHAR(50),
   registration_date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);